spring:
  thymeleaf:
    mode: HTML5
  data:
    mongodb:
      host: dds-bp176d55b02fb394-pub.mongodb.rds.aliyuncs.com
      port: 3717
      database: csrs

mvc:
  view:
    prefix: /templates/
    suffix: .html
  static-path-pattern: /static/**

