spring:
  thymeleaf:
    mode: HTML5
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: test1

mvc:
  view:
    prefix: /templates/
    suffix: .html
  static-path-pattern: /static/**

